comment_width            = 80
format_strings           = true
group_imports            = "StdExternalCrate"
hard_tabs                = false
hex_literal_case         = "Lower"
imports_granularity      = "Crate"
max_width                = 80
newline_style            = "Unix"
reorder_impl_items       = true
reorder_imports          = true
use_field_init_shorthand = true
wrap_comments            = true
